// 'use Client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import CarProvider from '@/context/CarProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Binar Car Rental',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} max-w-[1440px] mx-auto`}
      >
        <CarProvider>
          <Header />
          {children}
          <Footer />
        </CarProvider>
      </body>
    </html>
  )
}
